// ============================================================
//  APEX VIDEO ENGINE — DROP 16 — BARRETT M82
//  Target: ~48-52 seconds | 4 scenes | no bgMusic
//  Testing new feature: stock-image-sequence + rotate-cw/ccw
// ============================================================
const config = {
    output: {
        title:      'drop-16-barrettm82',
        format:     'portrait',
        fps:        30,
        crf:        24,
        preset:     'ultrafast',
        cleanup:    true,
        postProcess: {
            grain:            true,
            grainStrength:    0.028,
            vignette:         true,
            vignetteStrength: 0.58,
        },
    },
    defaults: {
        voice:              'bm_george',
        transition:         'fade',
        transitionDuration: 0.3,
    },
    scenes: [

        // ── SCENE 1 — HOOK (~10 sec) — NEVER CHANGE ──────────────
        {
            tts: {
                text:       'One weapon has been used in more conflicts than any other firearm in human history. Over one hundred million units exist today. It was designed by a man who was never formally trained as an engineer.',
                speed:      0.87,
                emotion:    'dramatic',
                pauseAfter: 0.5,
            },
            transition:         'zoom-cut',
            transitionDuration: 0.2,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'Barrett M82 rifle',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'zoom-in',
                    kenBurnsAmount: 0.13,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.58)' },
                {
                    type:       'text',
                    text:       'THE GUN THAT\nCHANGED\nTHE WORLD',
                    x:          540,
                    y:          700,
                    fontSize:   92,
                    fontFamily: 'Arial Black, Impact, sans-serif',
                    fontWeight: 'bold',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   940,
                    lineHeight: 1.1,
                    gradient:   ['#f5c518', '#ff8c00'],
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 6,
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   36,
                    animation:  'pop',
                    animDur:    0.4,
                    startT:     0.2,
                    hookLayer:  true,
                },
            ],
        },

        // ── SCENE 2 — THE PERSON (~9 sec) — name + struggle, nothing else ──
        {
            tts: {
                text:       'Ronnie Barrett. A professional photographer, not a gunsmith. He saw a photo of a fifty caliber machine gun on a river boat and asked why no rifle existed to fire that round — so he built one himself.',
                speed:      0.87,
                emotion:    'dramatic',
                pauseAfter: 0.4,
            },
            transition:         'wipe-left',
            transitionDuration: 0.28,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'garage workshop tools',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'pan-up',
                    kenBurnsAmount: 0.2,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.55)' },
                {
                    type:       'split-reveal',
                    text:       'A PHOTOGRAPHER\nBUILT THIS.',
                    x:          540,
                    y:          420,
                    fontSize:   66,
                    fontFamily: 'Impact, Arial Black, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    splitGap:   8,
                    animDur:    0.45,
                    gradient:   ['#f5c518', '#ff8c00'],
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   30,
                    startT:     0.2,
                },
                {
                    type:       'text',
                    text:       'Drawn on his dining table.\nBuilt in a gravel-floor garage.',
                    x:          540,
                    y:          650,
                    fontSize:   44,
                    fontFamily: 'Arial Black, Impact, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   880,
                    lineHeight: 1.3,
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 4,
                    animation:  'fade',
                    animDur:    0.35,
                    startT:     0.6,
                },
            ],
        },

        // ── SCENE 3 — DESIGN PHILOSOPHY (~18 sec) — new feature test ──
        //  stock-image-sequence with 4 close-up slides + rotate accents
        {
            tts: {
                text:       'His philosophy was brute simplicity. No rifle fired a fifty caliber round semi-automatically before this. He engineered the recoil system by hand, in his garage, until a single man could fire the same round built for a vehicle-mounted machine gun.',
                speed:      0.87,
                emotion:    'dramatic',
                pauseAfter: 0.5,
            },
            transition:         'glitch',
            transitionDuration: 0.26,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:     'stock-image-sequence',
                    queries: [
                        'Barrett M82 muzzle brake closeup',
                        'Barrett M82 bolt mechanism open',
                        '.50 caliber BMG round closeup',
                        'Barrett M82 rifle scope mounted',
                    ],
                    source:   'serpapi',
                    fit:      'cover',
                    kenBurnsSequence: [
                        { kenBurns: 'zoom-in',    kenBurnsAmount: 0.3 },
                        { kenBurns: 'rotate-cw',  kenBurnsAmount: 0.28, rotateDeg: 9 },
                        { kenBurns: 'pan-left',   kenBurnsAmount: 0.28 },
                        { kenBurns: 'rotate-ccw', kenBurnsAmount: 0.28, rotateDeg: 9 },
                    ],
                    x: 0, y: 0, width: 1080, height: 1920,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.42)' },
                {
                    type:       'text',
                    text:       'FIRST SEMI-AUTO\n.50 CALIBER\nRIFLE EVER MADE.',
                    x:          540,
                    y:          650,
                    fontSize:   68,
                    fontFamily: 'Impact, Arial Black, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   900,
                    lineHeight: 1.15,
                    gradient:   ['#f5c518', '#ff8c00'],
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 5,
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   24,
                    animation:  'pop',
                    animDur:    0.35,
                    startT:     0.3,
                },
                {
                    type:       'text',
                    text:       'A round built for\nvehicle-mounted machine guns —\nnow fired by one man.',
                    x:          540,
                    y:          1020,
                    fontSize:   42,
                    fontFamily: 'Arial Black, Impact, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   900,
                    lineHeight: 1.25,
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 4,
                    animation:  'fade',
                    animDur:    0.35,
                    startT:     1.4,
                },
            ],
        },

        // ── SCENE 4 — PUNCH + CTA (~11 sec) ──────────────────────
        {
            tts: {
                text:       'Over sixty countries now use the weapon that started as hand-drawn blueprints on a kitchen table. A photographer with no engineering background built the most powerful sniper rifle in modern warfare. Subscribe for more gun stories most people never hear.',
                speed:      0.87,
                emotion:    'dramatic',
                pauseAfter: 0.7,
            },
            transition:         'zoom-cut',
            transitionDuration: 0.2,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'Barrett M82 rifle',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'zoom-out',
                    kenBurnsAmount: 0.16,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.58)' },
                {
                    type:       'text',
                    text:       '60+ COUNTRIES.\nONE KITCHEN TABLE.',
                    x:          540,
                    y:          420,
                    fontSize:   66,
                    fontFamily: 'Impact, Arial Black, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   940,
                    lineHeight: 1.2,
                    gradient:   ['#f5c518', '#ff8c00'],
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 5,
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   26,
                    animation:  'slide-up',
                    animDur:    0.34,
                    startT:     0.3,
                },
                {
                    type:        'notification-card',
                    x:           540,
                    y:           1370,
                    width:       860,
                    title:       '🔔 Subscribe for more',
                    body:        'Gun history most people never hear',
                    bgColor:     'rgba(245,197,24,0.14)',
                    borderColor: '#f5c518',
                    titleColor:  '#f5c518',
                    bodyColor:   '#ffffff',
                    fontSize:    34,
                    bodySize:    27,
                    borderRadius:18,
                    animation:   'slide-up',
                    animDur:     0.35,
                    startT:      1.5,
                },
            ],
        },
    ],
};

module.exports = config;
