// ============================================================
//  APEX VIDEO ENGINE — DROP 14 — MP5 (LEAN CUT)
//  Target: ~45-50 seconds | 4 scenes | no bgMusic | no list-reveal
// ============================================================
const config = {
    output: {
        title:      'drop-14-mp5',
        format:     'portrait',
        fps:        30,
        crf:        24,
        preset:     'ultrafast',
        cleanup:    true,
        postProcess: {
            grain:            true,
            grainStrength:    0.028,
            vignette:         true,
            vignetteStrength: 0.58,
        },
    },
    defaults: {
        voice:              'bm_george',
        transition:         'fade',
        transitionDuration: 0.34,
    },
    scenes: [

        // ── SCENE 1 — HOOK (~10 sec) — NEVER CHANGE ──────────────
        {
            tts: {
                text:       'One weapon has been used in more conflicts than any other firearm in human history. Over one hundred million units exist today. It was designed by a man who was never formally trained as an engineer.',
                speed:      0.87,
                emotion:    'dramatic',
                pauseAfter: 0.5,
            },
            transition:         'zoom-cut',
            transitionDuration: 0.2,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'MP5 submachine gun black',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'zoom-in',
                    kenBurnsAmount: 0.13,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.58)' },
                {
                    type:       'text',
                    text:       'THE GUN THAT\nCHANGED\nTHE WORLD',
                    x:          540,
                    y:          700,
                    fontSize:   92,
                    fontFamily: 'Arial Black, Impact, sans-serif',
                    fontWeight: 'bold',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   940,
                    lineHeight: 1.1,
                    gradient:   ['#f5c518', '#ff8c00'],
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 6,
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   36,
                    animation:  'pop',
                    animDur:    0.4,
                    startT:     0.2,
                    hookLayer:  true,
                },
            ],
        },

        // ── SCENE 2 — THE PERSON (~8 sec) — name + struggle, nothing else ──
        {
            tts: {
                text:       'Ludwig Vorgrimler. A German engineer whose own country banned him from building weapons after the war — so he fled to Spain, then France, perfecting his design in exile before he could ever bring it home.',
                speed:      0.87,
                emotion:    'dramatic',
                pauseAfter: 0.4,
            },
            transition:         'wipe-left',
            transitionDuration: 0.30,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'post war German engineer',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'pan-up',
                    kenBurnsAmount: 0.24,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.55)' },
                {
                    type:       'split-reveal',
                    text:       'BANNED\nFROM BUILDING.',
                    x:          540,
                    y:          420,
                    fontSize:   80,
                    fontFamily: 'Impact, Arial Black, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    splitGap:   8,
                    animDur:    0.5,
                    gradient:   ['#f5c518', '#ff8c00'],
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   30,
                    startT:     0.2,
                },
                {
                    type:       'text',
                    text:       'Perfected it in exile\nbefore he ever\ncame home.',
                    x:          540,
                    y:          640,
                    fontSize:   48,
                    fontFamily: 'Arial Black, Impact, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   860,
                    lineHeight: 1.3,
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 4,
                    animation:  'fade',
                    animDur:    0.4,
                    startT:     0.6,
                },
            ],
        },

        // ── SCENE 3 — DESIGN PHILOSOPHY (~15 sec) — why it was good ──
        {
            tts: {
                text:       'His philosophy was accuracy over chaos. Most submachine guns of the era fired from an open bolt, jerking wildly with every shot. He scaled down a battle rifle\'s locking system instead — giving a compact weapon rifle-like precision, shot after shot.',
                speed:      0.87,
                emotion:    'dramatic',
                pauseAfter: 0.5,
            },
            transition:         'glitch',
            transitionDuration: 0.26,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'MP5 disassembled mechanism',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'drift',
                    kenBurnsAmount: 0.13,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.52)' },
                {
                    type:       'text',
                    text:       'RIFLE PRECISION.\nPISTOL SIZE.',
                    x:          540,
                    y:          650,
                    fontSize:   78,
                    fontFamily: 'Impact, Arial Black, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   880,
                    lineHeight: 1.15,
                    gradient:   ['#f5c518', '#ff8c00'],
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 5,
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   24,
                    animation:  'pop',
                    animDur:    0.4,
                    startT:     0.3,
                },
                {
                    type:       'text',
                    text:       'The first submachine gun\nbuilt for real accuracy.',
                    x:          540,
                    y:          980,
                    fontSize:   48,
                    fontFamily: 'Arial Black, Impact, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   900,
                    lineHeight: 1.25,
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 4,
                    animation:  'fade',
                    animDur:    0.4,
                    startT:     1.2,
                },
            ],
        },

        // ── SCENE 4 — PUNCH + CTA (~12 sec) — loops back to hook frame ──
        {
            tts: {
                text:       'It became the gold standard for special forces in over forty countries — the weapon of choice for the world\'s most elite counter-terrorism units. But to most people, it\'s just the gun from every video game they\'ve ever played. There\'s a stranger detail about this gun most people never hear.',
                speed:      0.87,
                emotion:    'dramatic',
                pauseAfter: 0.7,
            },
            transition:         'zoom-cut',
            transitionDuration: 0.2,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'MP5 submachine gun black',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'zoom-in',
                    kenBurnsAmount: 0.18,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.58)' },
                {
                    type:       'text',
                    text:       '40+ COUNTRIES.\nA VIDEO GAME PROP\nTO MOST PEOPLE.',
                    x:          540,
                    y:          420,
                    fontSize:   62,
                    fontFamily: 'Impact, Arial Black, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   940,
                    lineHeight: 1.2,
                    gradient:   ['#f5c518', '#ff8c00'],
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 5,
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   26,
                    animation:  'slide-up',
                    animDur:    0.36,
                    startT:     0.3,
                },
                {
                    type:        'notification-card',
                    x:           540,
                    y:           1370,
                    width:       860,
                    title:       '🔎 Stranger than fiction.',
                    body:        'The real story behind the gun most people only know from games.',
                    bgColor:     'rgba(245,197,24,0.14)',
                    borderColor: '#f5c518',
                    titleColor:  '#f5c518',
                    bodyColor:   '#ffffff',
                    fontSize:    34,
                    bodySize:    26,
                    borderRadius:18,
                    animation:   'slide-up',
                    animDur:     0.4,
                    startT:      1.6,
                },
            ],
        },
    ],
};

module.exports = config;
