// ============================================================
//  APEX VIDEO ENGINE — DROP 15B — PUCKLE GUN (45-SEC CUT)
//  Target: ~45 seconds | 4 scenes | no bgMusic | no list-reveal
//  NOTE: custom hook this drop only — generic "most conflicts"
//        hook doesn't fit a weapon that never saw combat.
// ============================================================
const config = {
    output: {
        title:      'drop-15b-pucklegun-45s',
        format:     'portrait',
        fps:        30,
        crf:        24,
        preset:     'ultrafast',
        cleanup:    true,
        postProcess: {
            grain:            true,
            grainStrength:    0.028,
            vignette:         true,
            vignetteStrength: 0.58,
        },
    },
    defaults: {
        voice:              'bm_george',
        transition:         'fade',
        transitionDuration: 0.3,
    },
    scenes: [

        // ── SCENE 1 — CUSTOM HOOK (~11 sec) ──────────────────────
        {
            tts: {
                text:       'One gun was designed to decide who deserved mercy — by the shape of its bullet. Built in 1718, a century before anyone thought a machine gun was even possible.',
                speed:      0.9,
                emotion:    'dramatic',
                pauseAfter: 0.4,
            },
            transition:         'zoom-cut',
            transitionDuration: 0.2,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'Puckle gun flintlock',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'zoom-in',
                    kenBurnsAmount: 0.13,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.58)' },
                {
                    type:       'text',
                    text:       'THE GUN\nDESIGNED TO PICK\nWHO SUFFERED MORE',
                    x:          540,
                    y:          700,
                    fontSize:   76,
                    fontFamily: 'Arial Black, Impact, sans-serif',
                    fontWeight: 'bold',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   940,
                    lineHeight: 1.1,
                    gradient:   ['#f5c518', '#ff8c00'],
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 6,
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   36,
                    animation:  'pop',
                    animDur:    0.4,
                    startT:     0.2,
                    hookLayer:  true,
                },
            ],
        },

        // ── SCENE 2 — THE PERSON (~7 sec) ────────────────────────
        {
            tts: {
                text:       'James Puckle. Not a soldier. Not an engineer. A London lawyer who patented the world\'s first machine gun.',
                speed:      0.9,
                emotion:    'dramatic',
                pauseAfter: 0.3,
            },
            transition:         'wipe-left',
            transitionDuration: 0.3,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'London 1700s lawyer portrait',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'pan-up',
                    kenBurnsAmount: 0.2,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.55)' },
                {
                    type:       'split-reveal',
                    text:       'A LAWYER\nBUILT THIS.',
                    x:          540,
                    y:          500,
                    fontSize:   88,
                    fontFamily: 'Impact, Arial Black, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    splitGap:   8,
                    animDur:    0.4,
                    gradient:   ['#f5c518', '#ff8c00'],
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   30,
                    startT:     0.2,
                },
                {
                    type:       'text',
                    text:       'Zero engineering\nbackground.',
                    x:          540,
                    y:          700,
                    fontSize:   50,
                    fontFamily: 'Arial Black, Impact, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   860,
                    lineHeight: 1.3,
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 4,
                    animation:  'fade',
                    animDur:    0.3,
                    startT:     0.5,
                },
            ],
        },

        // ── SCENE 3 — DESIGN PHILOSOPHY (~11 sec) ────────────────
        {
            tts: {
                text:       'One cylinder. Two kinds of ammunition. Round bullets for Christian enemies. Square bullets, meant to wound worse, reserved only for the Ottoman Turks.',
                speed:      0.9,
                emotion:    'dramatic',
                pauseAfter: 0.4,
            },
            transition:         'glitch',
            transitionDuration: 0.24,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'Puckle gun cylinder mechanism',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'drift',
                    kenBurnsAmount: 0.13,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.52)' },
                {
                    type:       'text',
                    text:       'ROUND BULLETS.\nSQUARE BULLETS.\nONE GUN.',
                    x:          540,
                    y:          700,
                    fontSize:   76,
                    fontFamily: 'Impact, Arial Black, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   880,
                    lineHeight: 1.15,
                    gradient:   ['#f5c518', '#ff8c00'],
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 5,
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   24,
                    animation:  'pop',
                    animDur:    0.35,
                    startT:     0.3,
                },
                {
                    type:       'text',
                    text:       'Written directly\ninto its 1718 patent.',
                    x:          540,
                    y:          1000,
                    fontSize:   46,
                    fontFamily: 'Arial Black, Impact, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   860,
                    lineHeight: 1.25,
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 4,
                    animation:  'fade',
                    animDur:    0.35,
                    startT:     1.1,
                },
            ],
        },

        // ── SCENE 4 — PUNCH + CTA (~10 sec) — loops to hook frame ──
        {
            tts: {
                text:       'The military called it too advanced to trust. Only one was ever sold — never to an army. Subscribe for more gun stories most people never hear.',
                speed:      0.9,
                emotion:    'dramatic',
                pauseAfter: 0.6,
            },
            transition:         'zoom-cut',
            transitionDuration: 0.2,
            captions: {
                style:          'highlight',
                position:       'bottom',
                fontSize:       60,
                color:          '#ffffff',
                highlightColor: '#f5c518',
                wordsPerChunk:  3,
                strokeColor:    'rgba(0,0,0,1)',
                strokeWidth:    7,
            },
            layers: [
                {
                    type:           'stock-image',
                    query:          'Puckle gun flintlock',
                    source:         'serpapi',
                    orientation:    'portrait',
                    imageIndex:     0,
                    x: 0, y: 0, width: 1080, height: 1920,
                    fit:            'cover',
                    kenBurns:       'zoom-in',
                    kenBurnsAmount: 0.16,
                },
                { type: 'overlay', color: 'rgba(0,0,0,0.58)' },
                {
                    type:       'text',
                    text:       '144 YEARS\nTOO SOON.',
                    x:          540,
                    y:          420,
                    fontSize:   76,
                    fontFamily: 'Impact, Arial Black, sans-serif',
                    color:      '#ffffff',
                    align:      'center',
                    maxWidth:   940,
                    lineHeight: 1.2,
                    gradient:   ['#f5c518', '#ff8c00'],
                    stroke:     true,
                    strokeColor:'#000000',
                    strokeWidth: 5,
                    glow:       true,
                    glowColor:  '#f5c518',
                    glowBlur:   26,
                    animation:  'slide-up',
                    animDur:    0.32,
                    startT:     0.3,
                },
                {
                    type:        'notification-card',
                    x:           540,
                    y:           1370,
                    width:       860,
                    title:       '🔔 Subscribe for more',
                    body:        'Gun history most people never hear',
                    bgColor:     'rgba(245,197,24,0.14)',
                    borderColor: '#f5c518',
                    titleColor:  '#f5c518',
                    bodyColor:   '#ffffff',
                    fontSize:    34,
                    bodySize:    27,
                    borderRadius:18,
                    animation:   'slide-up',
                    animDur:     0.35,
                    startT:      1.3,
                },
            ],
        },
    ],
};

module.exports = config;
